---
 
input:
  samples: path/to/inputsamplesheet.tsv
  bed: path/to/3UTR.bed
  refgenome: path/to/genome.fa
  snps: path/to/SNPfile.vcf
  summmaryfile: path/to/summaryfile.tsv
  summaryname: yoursamplename

output: path/to/outputdirectory/ # output directory

params:
  cores: 1 # number of cores for multi-processing
  gpus: null # if CUDA GPUs are available, specify number here
  readorientation: reverse # alternative: forward
  filterstrategy: pseudosingleend # alternative: singleend
  model: twocompartment # or choose 'onecompartment'

emparams:
  uridinethreshold: 30
  minimumcoverage: 100

...
