name: Halfpipe
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - matplotlib
  - nextgenmap
  - numpy
  - pandas
  - pysam
  - pyyaml
  - r-argparse
  - r-base
  - r-deoptim
  - r-doparallel
  - r-foreach
  - r-mcmc
  - r-sjstats
  - scipy
